controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    hardware_interface: "FrankaHardwareInterface"
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    franka_arm_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7

franka_arm_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    interface_name: position
